### ISSUE TITLE
Enemy spawner

### ISSUE THREAD

**Issue by daniellimws** [jeffsieu/last-man-sitting#112]
Ideas pls

**Comment by jeffsieu** [comment]
Enemy spawner as in how to spawn the enemies in each room?

**Comment by jeffsieu** [comment]
I think we should have each room spawn and keep track of the enemies it has spawned. Once those enemies died, it should unlock adjacent rooms.

**Comment by daniellimws** [comment]
Sounds good to have each room keep track.
