### ISSUE TITLE
Use `MoveAndSlide` to move bullet

### ISSUE THREAD

**Issue by daniellimws** [jeffsieu/last-man-sitting#115]
Now the bullet moves by manually modifying `Translation`. So it doesn't collide with the wall.

**Comment by daniellimws** [comment]
Now the `Bullet` is an `Area` instead of `KinematicBody`. Being an `Area`, we can use the `on_body_entered` signal, which is not available for a `KinematicBody`. Logically, a bullet should be a `KinematicBody`. So have to change the whole enemy collision detection as well I think.

**Comment by jeffsieu** [comment]
why dowan use the get slide collision method?

**Comment by jeffsieu** [comment]
oh, I think we should change it to KinematicBody, then can just move the code from body_entered to loop through GetSlideCollision

**Comment by daniellimws** [comment]
yes once changed then can use `GetSlideCollision`

**Comment by daniellimws** [comment]
Alright some problems with the current implementation of Projectile

- Should be a `RigidBody` and use `ApplyCentralImpulse` in `_Ready`
- The `Bullet` is a child inside a `Projectile` object, hence `_PhysicsProcess` is called on `Projectile` as a container, not the `PackedScene` instance (i.e. `Bullet`). Keep this in mind because any physics engine functions will not work properly because the physics is applied to the `Projectile`, not the actual `Bullet` with the collider. nam sain

Makes me think if we should change the way projectiles are instantiated. Since each projectile is already add to a `projectileContainer` (i.e. the `Level`), I don't think we should put them inside a `Projectile` object that does nothing except being a container. We should attach a script to each projectile scene (for example Bullet.tscn) instead.

**Comment by daniellimws** [comment]
Ok not a bug
