### ISSUE TITLE
Damage multiplier for continuous firing

### ISSUE THREAD

**Issue by jeffsieu** [jeffsieu/last-man-sitting#17]
We can consider adding a damage multiplier when the player shoots continuously, so as to incentivise this. Intention is for them to have to choose between damage or safety, cos if they keep shooting it's harder to control their movement

**Comment by daniellimws** [comment]
Should the player know this explicitly?

**Comment by jeffsieu** [comment]
Ya, actually can either have this by default or as an upgrade.
