### ISSUE TITLE
Loot system

### ISSUE THREAD

**Issue by jeffsieu** [jeffsieu/last-man-sitting#3]
A generic looting system is required for the game, since enemies may drop loot/experience.

**Comment by jeffsieu** [comment]
Need to make generic droppable, then for now make experience orbs and some crystal cutrency

**Comment by daniellimws** [comment]
Experience orbs sial

**Comment by daniellimws** [comment]
Hmm I think this loot system is for each level nia. Then later we make another one that keeps track of overall loot for the entire game.

**Comment by jeffsieu** [comment]
Maybe this should be CollectibleManager, while the main loot one will be a Persist node like in [here](https://docs.godotengine.org/en/3.1/tutorials/io/saving_games.html)

**Comment by daniellimws** [comment]
Ok we can close this once #23 is merged, then continue this with #20
