### ISSUE TITLE
Level generation

### ISSUE THREAD

**Issue by jeffsieu** [jeffsieu/last-man-sitting#87]
We need to generate levels. As of now, we can focus on handcrafted levels until we find a sweet spot for what kind of layout the level should have. Nevertheless it might be good to make a layer of abstraction where we can easily create corridors, rooms and such.

**Comment by daniellimws** [comment]
Oops duplicated in #90. Look at #101 and #102 for more details. Keeping this open for discussion.

**Comment by daniellimws** [comment]
Actually I don't think we will discuss anything here. Gonna close it to tidy things up.
