### ISSUE TITLE
Map parsing system

### ISSUE THREAD

**Issue by daniellimws** [jeffsieu/last-man-sitting#90]
We should be able to add a `LevelGenerator` node that takes a map image and parses it, creating rooms and corridors.

- [x] Can generate a floor and wall meshes
- [ ] Floor meshes are optimised (same mesh per classroom floor, as different classroom may have different floors)
- [ ] Generate different rooms (e.g. library, canteen; based on pixel color)
- [ ] Generate a map with labels for the different rooms

![2020-04-30 22 50 30](https://user-images.githubusercontent.com/8130120/80725035-2516cc00-8b35-11ea-893a-acbfe8a9d62c.jpg)

Should be encoded like this

![image](https://user-images.githubusercontent.com/8130120/80726035-7bd0d580-8b36-11ea-8c15-56bdff2c476a.png)

Export as raw image data (available in GIMP idk about others). One pixel is one cell unit in the game. White cells are walls. Different colours mean different rooms.

The current room generator might need to be changed for this.

**Comment by starcasted** [comment]
nice

**Comment by daniellimws** [comment]
Implementation idea is:
- Process the image to detect rooms (can use bfs, i think now the simple way to implement is to detect rectangle rooms, so for junctions split them into multiple rooms) and walls aren't included in a room. The room will be a plane mesh then we can attach a shader to generate the floor based on a texture.
- Similarly, detect walls, then make cube mesh. Can optimize this later if needed.

**Comment by daniellimws** [comment]
Work continued in #101 and #102
